version: "3"
services:
  osrm_car:
    image: osrm/osrm-backend
    restart: always
    volumes:
      - ./bkk/car:/data
    command: osrm-routed --algorithm mld -p 5000 /data/custom.osrm
    expose:
      - 5000

  osrm_walk:
    image: osrm/osrm-backend
    restart: always
    volumes:
      - ./bkk/walk:/data
    command: osrm-routed --algorithm mld -p 5000 /data/custom.osrm
    expose:
      - 5000
