version: "3"
services:
  car-routing:
    image: osrm/osrm-backend:v5.22.0
    restart: always
    volumes:
      - ./bkk/car:/data
    networks:
      - proxy_default
    command: osrm-routed --algorithm mld -p 5000 /data/custom.osrm
    expose:
      - 5000

  walk-routing:
    image: osrm/osrm-backend:v5.22.0
    restart: always
    volumes:
      - ./bkk/walk:/data
    networks:
      - proxy_default
    command: osrm-routed --algorithm mld -p 5000 /data/custom.osrm
    expose:
      - 5000


networks:
  proxy_default:
    external: true

