version: "3.7"
services:
  caddy:
    image: abiosoft/caddy:no-stats
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./:/code
    ports:
      - "1180:2015"

  osrm_car:
    image: osrm/osrm-backend
    ports:
      - "5000:5000"
    volumes:
      - ./bkk/car:/data
    command: osrm-routed --algorithm mld -p 5000 /data/custom.osrm

  osrm_walk:
    image: osrm/osrm-backend
    ports:
      - "5001:5000"
    volumes:
      - ./bkk/walk:/data
    command: osrm-routed --algorithm mld -p 5000 /data/custom.osrm
